# Generated by Django 5.0.1 on 2024-10-29 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '4. Brand'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '5. Category'},
        ),
        migrations.AlterModelOptions(
            name='sub_category',
            options={'verbose_name_plural': '3. Sub_Category'},
        ),
        migrations.AddField(
            model_name='product',
            name='additional_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.additional_information'),
        ),
    ]
