# Generated by Django 5.0.1 on 2024-10-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_arm_style_remove_product_assembly_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='additional_information',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='additional_information',
            name='update_at',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product_Product',
        ),
    ]
