# Generated by Django 5.0.1 on 2024-10-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '10. Banner'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name_plural': '7. Offer'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '8. Slider'},
        ),
    ]
