# Generated by Django 5.0.1 on 2024-10-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_header_footer_color_setting_nav_color_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='footer_color_1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='setting',
            name='footer_color_2',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
